export const defaultState = {
    wronAnswerNoticeActive: false,
    rightAnswerNotiseActive: false,    
    questionNotiseActive: false,
    numberOfCurrentQuestion: 1,
    modal: false,    
    countAnswers: 0,
    answer: "...",
    navbarButton_Main: true,
    navbarButton_About: false,
    navbarButton_Contacts: false,
    navbarButton_Registration: false,
    navbarButton_QuestionPage: false,
    navbarButton_rules: false,
};